#!/bin/bash
#PBS -l nodes=1:ppn=2
#PBS -N preproccessLumosVar
#PBS -l walltime=16:00:00
#PBS -m abe
#PBS -M rhalperin@tgen.org
#PBS -j oe

cd $PBS_O_WORKDIR

module load MCR/9.0

TMPDIR=/scratch/rhalperin/TMP_$RANDOM
mkdir $TMPDIR
echo "Running MultiSampleCaller"
echo "CONFIG is ${CONFIG}"
echo "CHR is ${CHR}"
export MCR_CACHE_ROOT=$TMPDIR
export TMP=$TMPDIR
echo "Cache going to $TMPDIR"
IFS='. ' read -a NAMES <<< $CONFIG
echo NAME is ${NAMES[0]}

date
./lumosVarPreprocess ${CONFIG} ${CHR}
if [ $? -eq 0 ] ; then
	touch ${NAMES[0]}_Step${CHR}.lumosVarPass
else
	touch ${NAMES[0]}_Step${CHR}.lumosVarFail
fi
rm ${NAMES[0]}_Step${CHR}.lumosVarInQueue
date

rm -r $TMPDIR
